include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    invalid_dependency: ignore

linter:
  rules:
    prefer_const_constructors: false
    prefer_const_literals_to_create_immutables: false
