name: passes_box
description: A password manager application with high-level encryption, no-sql database and MVVM architecture for Android, iOS and web.


version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  get: any
  shared_preferences: any
  file_saver: any
  file_picker: any
  permission_handler: any
  encrypt: any
  url_launcher: any
  local_auth: any
  hive: any
  hive_flutter: any
  sqflite: any
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: any

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: raleway
      fonts:
        - asset: assets/fonts/raleway.ttf
