name: passes_box
description: A password manager application with high-level encryption, no-sql database and MVVM architecture for Android, iOS and web.
homepage: https://github.com/gabrimatic/passesbox_readme

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter_secure_storage: any
  url_strategy: any
  universal_html: any
  get: any
  shared_preferences: any
  file_saver: any
  file_picker: any
  permission_handler: any
  encrypt: any
  url_launcher: any
  local_auth: any
  hive: any
  hive_flutter: any
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: any
  hive_generator: any
  build_runner: any

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: raleway
      fonts:
        - asset: assets/fonts/raleway.ttf
